name: Create Archive

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: pull latest and remove old file from repo
      run: |
        git config --global user.name "panda-hackerman"
        git config --global user.email "panda-hackerman@users.noreply.github.com"
        git config pull.rebase false
        git pull
        rm -f release.zip
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        filename: 'release.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - name: push changes to remote
      run: |
        git add -A
        git commit -m "new pack"
        git push --force
  convert-bedrock-pack:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 17
      - name: Install dependencies
        run: |
          sudo apt-get install -y moreutils zip
          yarn global add spritesheet-js
      - name: Convert pack
        id: convert-pack
        continue-on-error: false
        run: |
          git clone https://github.com/Kas-tle/java2bedrock.sh.git
          mkdir -p java2bedrock.sh/staging
          cp java2bedrock.sh/converter.sh java2bedrock.sh/staging
          cp release.zip java2bedrock.sh/staging
          cd java2bedrock.sh/staging
          chmod +x converter.sh
          ./converter.sh release.zip -w "false" -m "null" -a "entity_alphatest_one_sided" -b "alpha_test" -f "null" -v "1.19.2"
      - name: Upload converted pack
        uses: actions/upload-artifact@v3
        with:
          name: Pack Files
          path: |
            java2bedrock.sh/staging/target/packaged/geyser_resources.mcpack
            java2bedrock.sh/staging/target/packaged/geyser_addon.mcaddon
            java2bedrock.sh/staging/target/geyser_mappings.json
            java2bedrock.sh/staging/config.json
